{
 "title": "Traefik",
 "description": "Traefik dashboard prometheus",
 "tags": [
  "traefik",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(traefik_config_reloads_total, namespace)"
   },
   { "name": "percentiles", "query": "95,99" },
   { "name": "backend", "query": "label_values(backend)" }
  ]
 },
 "panels": [
  {
   "title": "traefik 5分钟每秒请求数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{endpoint=\"http-metrics\"}[5m])) by (protocol)",
     "legendFormat": "traefik:{{protocol}}"
    }
   ]
  },
  {
   "title": "traefik响应 $percentiles 数据 th perc over 5 min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, rate(traefik_entrypoint_request_duration_seconds_bucket{namespace=\"$namespace\",code=\"200\",entrypoint=\"http\",protocol=\"http\",method=\"GET\"}[5m]))",
     "legendFormat": "{{instance}}:{{protocol}}"
    }
   ]
  },
  {
   "title": "前端 Open Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(traefik_entrypoint_open_connections{namespace=\"$namespace\"}) by (method))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "后端 Open Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(traefik_backend_open_connections{namespace=\"$namespace\"}) by (method))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  { "title": "Pods ressources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "域名状态分析",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{endpoint=\"http-metrics\"}[5m])) by (backend)"
    },
    {
     "expr": "sum(rate(traefik_backend_request_duration_seconds_sum{code=\"200\",method=\"GET\",protocol=\"http\"}[5m])) by (backend)/sum(rate(traefik_backend_request_duration_seconds_count{code=\"200\",method=\"GET\",protocol=\"http\"}[5m])) by (backend)"
    },
    {
     "expr": "sum(rate(traefik_backend_request_duration_seconds_sum{code=\"200\",method=\"GET\",protocol=\"http\"}[5m]offset 24h)) by (backend)/sum(rate(traefik_backend_request_duration_seconds_count{code=\"200\",method=\"GET\",protocol=\"http\"}[5m]offset 24h)) by (backend)"
    },
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"200|206\"}[5m])) by(backend) / sum(rate(traefik_backend_requests_total[5m])) by(backend)"
    },
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"301|302\"}[5m])) by(backend) / sum(rate(traefik_backend_requests_total[5m])) by(backend)"
    },
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"4..\"}[5m])) by(backend) / sum(rate(traefik_backend_requests_total[5m])) by(backend)"
    },
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"5..\"}[5m])) by(backend) / sum(rate(traefik_backend_requests_total[5m])) by(backend)"
    }
   ]
  }
 ]
}